"""empty message

Revision ID: 011765eb75f4
Revises: 6049786acb48
Create Date: 2024-05-15 16:33:51.662713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011765eb75f4'
down_revision = '6049786acb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('reviews',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('room_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reviews',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
